# -*- coding: utf-8 -*-
"""week1_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10e9ckxnc8u5ZhKEJFA5NfFnuK6IFE3oX
"""

import pandas as pd

df=pd.read_csv('data/jobs.csv', encoding='latin-1')
df.head()

df.shape

print(df.columns)

"""MISSING VALUES"""

#missing values of each column
print(df.isnull().sum())

"""KEEPING IMPORTANT COLUMNS(JOB TITLE, SALARY, DESCRIPTION)"""

df=df[['Job Title','Salary Estimate','Job Description']]
df.head()

df.shape

"""REMOVING ROWS WITH MISSING SALARY"""

df=df.dropna(subset=['Salary Estimate'])
df.head()

df.shape

"""CLEAN SALARY COLUMN"""

import re

def clean_salary(salary):
    salary = str(salary)

    # Remove text in brackets
    salary = salary.split("(")[0]

    # Find numbers
    nums = re.findall(r'\d+', salary)

    if len(nums) == 2:
        low = int(nums[0])
        high = int(nums[1])
        return (low + high) / 2

    return None

df["salary_cleaned"] = df["Salary Estimate"].apply(clean_salary)
df=df.dropna(subset='salary_cleaned')

"""CLEAN JOB DESCRIPTION TEXT"""

def clean_text(text):
    text = str(text).lower()  # convert to lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # remove special characters
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df["clean_description"] = df["Job Description"].apply(clean_text)

df[["clean_description"]].head()

df.shape
#data integrity has been maintained as no important columns has been lost during data cleaning

"""SAVE CLEAN DATASET"""

df.to_csv("outputs/cleaned_jobs.csv", index=False)

df.head()

