# -*- coding: utf-8 -*-
"""week4_Market_Insights+Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yniWM-icoH6aB2QRIe4tMKsGyZDM_wcY
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("outputs/week3_skill_intelligence.csv")

print(df.head())
print(df.columns)

df['skill'] = df['skill'].str.replace("[", "", regex=False)
df['skill'] = df['skill'].str.replace("]", "", regex=False)
df['skill'] = df['skill'].str.replace("'", "", regex=False)

df['skill'] = df['skill'].str.strip()

print(df.head())

top_demand = df.sort_values(by="demand", ascending=False)

print("Top Skills by Demand")
print(top_demand[['skill','demand']].head(10))

top_salary = df.sort_values(by="avg_salary", ascending=False)

print("Highest Paying Skills")
print(top_salary[['skill','avg_salary']].head(10))

top_skills = df.sort_values(by="skill_score", ascending=False)

print("Most Valuable Skills")
print(top_skills[['skill','skill_score']].head(10))

programming_skills = [
    'python','java','c++','c','r','scala'
]

data_analysis_skills = [
    'sql','statistics','excel','data analysis'
]

ml_skills = [
    'machine learning','deep learning','nlp','computer vision'
]

visualization_skills = [
    'tableau','power bi','matplotlib','seaborn'
]

cloud_bigdata_skills = [
    'spark','hadoop','aws','gcp','azure'
]

tools_skills = [
    'git','docker','kubernetes'
]

def categorize(skill):

    skill = skill.lower()

    if skill in programming_skills:
        return "Programming"

    elif skill in data_analysis_skills:
        return "Data Analysis"

    elif skill in ml_skills:
        return "Machine Learning"

    elif skill in visualization_skills:
        return "Visualization"

    elif skill in cloud_bigdata_skills:
        return "Cloud / Big Data"

    elif skill in tools_skills:
        return "Tools"

    else:
        return "Other"

df["category"] = df["skill"].apply(categorize)

def market_level(score):

    if score >= 0.6:
        return "High Value Skill"

    elif score >= 0.4:
        return "Strong Skill"

    else:
        return "Average Skill"

df['market_level'] = df['skill_score'].apply(market_level)

print(df.head())

top10 = df.sort_values(by="demand", ascending=False).head(10)

plt.figure(figsize=(10,6))
plt.barh(top10['skill'], top10['demand'])

plt.title("Top 10 Most In-Demand Skills")
plt.xlabel("Demand")
plt.ylabel("Skill")

plt.show()

category_counts = df['category'].value_counts()

plt.figure(figsize=(8,5))
category_counts.plot(kind='bar')

plt.title("Skill Category Distribution")
plt.xlabel("Category")
plt.ylabel("Count")

plt.show()

df.to_csv("outputs/week4_market_insights.csv", index=False)

print("Week 4 dataset saved successfully!")