# -*- coding: utf-8 -*-
"""week5_Skill_Recommendation_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKvuA3Z3BLZf6wrcxevvmNChs5QAdqjo
"""

import pandas as pd

df = pd.read_csv("outputs/week4_market_insights.csv")

print(df.head())

"""Step 3 — Create Skill Recommendation Function"""

def recommend_skills(user_skills, df, top_n=5):

    user_skills = [skill.lower() for skill in user_skills]

    df['skill'] = df['skill'].str.lower()

    # Remove skills already known
    recommendations = df[~df['skill'].isin(user_skills)]

    # Sort by skill_score
    recommendations = recommendations.sort_values(
        by="skill_score",
        ascending=False
    )

    return recommendations[['skill','skill_score','category']].head(top_n)

"""Step 4 — Test the Recommendation Engine"""

user_skills = ["python", "sql"]

recommendations = recommend_skills(user_skills, df)

print("User Skills:", user_skills)
print("\nRecommended Skills:")
print(recommendations)

"""Step 5 — Category-Based Recommendation (Smarter Version)"""

def category_recommendation(user_skills, df):

    user_skills = [skill.lower() for skill in user_skills]

    df['skill'] = df['skill'].str.lower()

    user_categories = df[df['skill'].isin(user_skills)]['category'].unique()

    recommendations = df[
        (df['category'].isin(user_categories)) &
        (~df['skill'].isin(user_skills))
    ]

    recommendations = recommendations.sort_values(
        by="skill_score",
        ascending=False
    )

    return recommendations[['skill','category','skill_score']].head(5)

"""Step 6 — Test Category Recommendation"""

user_skills = ["python", "sql"]

print("Category-Based Recommendations:")
print(category_recommendation(user_skills, df))

"""Step 7 — Opportunity Skill Recommendation"""

def opportunity_skills(df):

    top_opportunity = df.sort_values(
        by="opportunity_score",
        ascending=False
    )

    return top_opportunity[['skill','opportunity_score']].head(5)

"""Step 8 — Interactive User Input"""

user_input = input("Enter your skills separated by comma: ")

user_skills = user_input.lower().split(",")

user_skills = [skill.strip() for skill in user_skills]

print("\nRecommended Skills:")
print(recommend_skills(user_skills, df))