# -*- coding: utf-8 -*-
"""week3_Skill_Intelligence_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voChDkzkkiftnBhTpdjqmHLpwg_EiycW
"""

import pandas as pd

"""STEP 1: LOAD DATASET"""

df=pd.read_csv('outputs/week2_jobs_with_skills.csv')
df.head()

"""STEP2: CLEAN SKILL COLUMN"""

# Convert skills string to list
df["skills"] = df["skills"].fillna("")
df["skills"] = df["skills"].apply(lambda x: x.split(", "))

df.head()

"""STEP3: EXPLODE SKILLS"""

skills_df = df.explode("skills")
skills_df.head()

"""STEP4: SKILL DEMAND ANALYSIS"""

skill_demand = skills_df["skills"].value_counts().reset_index()
skill_demand.columns = ["skill", "demand"]

skill_demand.head(10)

"""STEP5: SALARY ANALYSIS PER SKILL"""

salary_analysis = skills_df.groupby("skills")["salary_cleaned"].mean().reset_index()
salary_analysis.columns = ["skill", "avg_salary"]

salary_analysis.head()

"""STEP6: MERGE DEMAND + SALARY"""

skill_intelligence = pd.merge(skill_demand, salary_analysis, on="skill")

skill_intelligence.head()

"""STEP7: NORMALIZE VALUES"""

def min_max_normalize(column):
    min_val = column.min()
    max_val = column.max()

    # Handle edge case: if all values are same
    if max_val == min_val:
        return 0  # or return column*0

    return (column - min_val) / (max_val - min_val)


# Apply normalization safely
skill_intelligence["demand_norm"] = min_max_normalize(
    skill_intelligence["demand"]
)

skill_intelligence["salary_norm"] = min_max_normalize(
    skill_intelligence["avg_salary"]
)

"""STEP8: CLEAN SCORING"""

# Simple & clean weights
demand_weight = 0.6
salary_weight = 0.4

skill_intelligence["skill_score"] = (
    demand_weight * skill_intelligence["demand_norm"] +
    salary_weight * skill_intelligence["salary_norm"]
)

"""STEP9: CLEAN RANKING"""

skill_intelligence = skill_intelligence.sort_values(
    by="skill_score",
    ascending=False
)

skill_intelligence["rank"] = range(1, len(skill_intelligence) + 1)

top_10_skills = skill_intelligence.head(10)

"""STEP10: DATA SAVING"""

# Final save step (Week 3 output)
skill_intelligence.to_csv("outputs/week3_skill_intelligence.csv", index=False)