# -*- coding: utf-8 -*-
"""week6_Skill_Gap_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bimXklnSkSXt6FiUlVuATj7r9K7LtSQ5
"""

import pandas as pd

# Load dataset
df = pd.read_csv("outputs/week4_market_insights.csv")
df['skill'] = df['skill'].str.lower()

# Role skill definitions
role_skills = {
    "data scientist": [
        "python", "sql", "machine learning",
        "statistics", "deep learning", "data visualization"
    ],
    "data analyst": [
        "sql", "excel", "tableau",
        "power bi", "statistics"
    ],
    "machine learning engineer": [
        "python", "machine learning",
        "deep learning", "tensorflow", "pytorch"
    ],
    "data engineer": [
        "python", "sql", "spark",
        "hadoop", "aws"
    ]
}


# ✅ Basic Skill Gap Function
def skill_gap(user_skills, target_role):
    user_skills = [skill.lower().strip() for skill in user_skills]
    target_role = target_role.lower().strip()

    if target_role not in role_skills:
        raise KeyError(target_role)

    required_skills = role_skills[target_role]

    missing_skills = [
        skill for skill in required_skills if skill not in user_skills
    ]

    return missing_skills


# ✅ Ranked Skill Gap Function (MAIN FUNCTION)
def ranked_skill_gap(user_skills, target_role, df):

    # Normalize input
    user_skills = [skill.lower().strip() for skill in user_skills]
    target_role = target_role.lower().strip()

    # Convert role keys to lowercase
    role_skills_lower = {k.lower(): v for k, v in role_skills.items()}

    # Role alias mapping
    role_alias = {
        "data analysis": "data analyst",
        "data analyst": "data analyst",
        "data scientist": "data scientist"
    }

    target_role = role_alias.get(target_role, target_role)

    # Check if role exists
    if target_role not in role_skills_lower:
        raise KeyError(target_role)

    # Required skills
    required = role_skills_lower[target_role]

    # Find missing skills
    missing_skills = [
        skill for skill in required if skill not in user_skills
    ]

    # Filter dataset for missing skills
    missing_df = df[df['skill'].isin(missing_skills)]

    # Handle empty result
    if missing_df.empty:
        return "No matching skills found in dataset."

    # Rank by importance
    ranked = missing_df.sort_values(
        by="skill_score",
        ascending=False
    )

    # Return top results
    return ranked[['skill', 'skill_score', 'category']].head(10)