# -*- coding: utf-8 -*-
"""week2_Skill_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwHFH8LmiqvAoecW6E6_DWKDxoIh7cpk
"""

import pandas as pd

"""STEP1: LOADING CLEANED DATASET"""

df=pd.read_csv('outputs/cleaned_jobs.csv')
df.head()

df.shape

"""STEP2: CREATE SKILL DICTIONARY"""

skills_list = [
    "python", "sql", "machine learning", "deep learning",
    "excel", "aws", "power bi", "tableau",
    "tensorflow", "pandas", "numpy", "nlp",
    "statistics", "data analysis", "r", "spark",
    "hadoop", "docker", "git", "scikit learn"
]

print("Total skills:", len(skills_list))

"""STEP3: EXTRACT SKILLS FROM TEXT"""

def extract_skills(text):
  found=[]
  for skill in skills_list:
    if skill in text:
      found.append(skill)
  return found
df['skills']=df['clean_description'].apply(extract_skills)
df[['clean_description','skills']].head()

"""STEP4: COUNT SKILL FREQUENCY"""

skill_counts=df['skills'].explode().value_counts()
print(skill_counts)

"""STEP5: VISUALIZE TOP SKILLS"""

import matplotlib.pyplot as plt

top_skills = skill_counts.head(10)

top_skills.plot(kind="bar")

plt.title("Top 10 Most Demanded Skills")
plt.xlabel("Skills")
plt.ylabel("Frequency")

plt.show()

#JOBS WITH NO SKILLS to vhevk wheather missing values have been handled or not
df[df["skills"].str.len() == 0]

"""STEP6: SAVE UPDATED DATASET"""

df.to_csv("outputs/week2_jobs_with_skills.csv", index=False)